### ISSUE TITLE
Is async highlighter support really needed?

### ISSUE THREAD

**Issue by puzrin** [jonschlinkert/remarked#11]
https://github.com/jonschlinkert/remarked/blob/master/index.js#L48-L122

There are `highlight.js` and one from google (used in twitter bootstrap), both sync. I don't know, is it legacy code, and is it really needed to support async pygmentize. But attempt to do async support and async highlight breacks architecture. IMHO hihglighter shoud be in renderer, and sync libs are enougth.

**Comment by jonschlinkert** [comment]
completely agreed!

**Comment by puzrin** [comment]
Fixed in master.
