### ISSUE TITLE
smartypants translation of dashes

### ISSUE THREAD

**Issue by attresearch** [jonschlinkert/remarked#14]
Smartypants translates '---' to an em-dash, and '--' to an en-dash.

remarked translates '--' to a dash and does not translate '---'.

I see that marked translates '--' and '---' properly, maybe you need to pull that change?

**Comment by jonschlinkert** [comment]
@attresearch, [this is deprecated](https://github.com/jonschlinkert/remarked#no-longer-maintained) in [favor of remarkable](https://github.com/jonschlinkert/remarkable)
