### ISSUE TITLE
Extended typographers support

### ISSUE THREAD

**Issue by outring** [jonschlinkert/remarked#8]
`smartypants` option is too simple and works well only with english language (i.e. other languages have different rules for quotes, etc.). So it would be great to have an option for custom typographer.

Important note: for russian language is important to know if we are at the beginning of sentence or not. To deal with it would be enough to pass a flag that we are at the beginning of block-level block .

I can implement it myself and make a pull request, but I'm not sure about how option should be passed (I mean, would it be another option, that have no deal with smartypants, or just function-value for smartypants).

What do you think?

**Comment by jonschlinkert** [comment]
> would it be another option, that have no deal with smartypants, or just function-value for smartypants

hmm, it might make sense to do both. e.g. add another method to the lexer, somewhere [before or after the smartypants regex](https://github.com/jonschlinkert/remarked/blob/master/lib/lexer-inline.js#L281), then add whatever logic is required [here](https://github.com/jonschlinkert/remarked/blob/master/lib/lexer-inline.js#L222-L232) or wherever it makes sense. I'm not sure how extensive this would be yet. 

I'm definitely in favor of making this more inclusive of other languages, so a pr would be great. would be great to have a few unit tests too. you could copy the [smartypants tests](https://github.com/jonschlinkert/remarked/blob/master/test/test_smartypants.js) or create new ones. feel free to implement the tests however you want. thanks!

**Comment by outring** [comment]
Yes, I've already done something like that. Will use separate option for now.
